manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: petejohanson
      remote: zmk
      revision: petejohanson:core/zephyr-3.4-update
      import: app/west.yml
  self:
    path: config
